# Generated by Django 2.2.3 on 2019-08-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
