# Generated by Django 2.2.3 on 2019-08-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('price', models.FloatField()),
                ('capital_adjusted', models.FloatField()),
                ('volume_traded', models.FloatField()),
                ('value_traded', models.FloatField()),
                ('number_of_trades', models.FloatField()),
                ('price_change', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('director_name', models.CharField(max_length=30)),
                ('director_role', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('overviews', models.TextField()),
                ('performance', models.TextField()),
                ('outlook', models.TextField()),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
    ]
