# Generated by Django 2.2.3 on 2019-08-05 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companyprofile_directors_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratios',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('market_cap', models.FloatField()),
                ('price_equity', models.FloatField()),
                ('EPS', models.FloatField()),
                ('NTA', models.FloatField()),
                ('DPS', models.FloatField()),
                ('beta_value', models.FloatField()),
                ('price_NTA', models.FloatField()),
                ('Net_yield', models.FloatField()),
                ('Sharpe', models.FloatField()),
                ('debt_equity', models.FloatField()),
                ('current', models.FloatField()),
                ('ROE', models.FloatField()),
                ('ROA', models.FloatField()),
                ('quick_ratio', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('payables', models.FloatField()),
                ('current_debt', models.FloatField()),
                ('current_liabilities', models.FloatField()),
                ('long_term_debt', models.FloatField()),
                ('deferred_tax_liabilities', models.FloatField()),
                ('other_NC_liabilities', models.FloatField()),
                ('NC_liability', models.FloatField()),
                ('total_liability', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeStatement',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('sales_revenue', models.FloatField()),
                ('investment_revenue', models.FloatField()),
                ('total_core_revenue', models.FloatField()),
                ('EB17DA', models.FloatField()),
                ('depreciation', models.FloatField()),
                ('EBIT', models.FloatField()),
                ('interest_expense', models.FloatField()),
                ('PBT', models.FloatField()),
                ('income_tax_expense', models.FloatField()),
                ('continuing_operations', models.FloatField()),
                ('MIE', models.FloatField()),
                ('net_income', models.FloatField()),
                ('basic_eps', models.FloatField()),
                ('diluted_eps', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('paid_in_capital', models.FloatField()),
                ('reatained_earnings', models.FloatField()),
                ('minority_interest', models.FloatField()),
                ('other_equity', models.FloatField()),
                ('total_equity', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('dividends', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CashTable',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('operating', models.FloatField()),
                ('investing', models.FloatField()),
                ('finance', models.FloatField()),
                ('net_change', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('cash_equity', models.FloatField()),
                ('NTR', models.FloatField()),
                ('current_inventory', models.FloatField()),
                ('other_CA', models.FloatField()),
                ('PPE', models.FloatField()),
                ('intangible_assests', models.FloatField()),
                ('LT_investments', models.FloatField()),
                ('LT_deferred_assets', models.FloatField()),
                ('other_NCA', models.FloatField()),
                ('current_assets', models.FloatField()),
                ('NC_assets', models.FloatField()),
                ('total_assets', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
    ]
