# Generated by Django 2.2.3 on 2019-08-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_assets_cashtable_dividends_equity_incomestatement_liabilities_ratios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='cashtable',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='companyprofile',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='directors',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='dividends',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='equity',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='incomestatement',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='liabilities',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='company',
            new_name='ticker',
        ),
        migrations.RenameField(
            model_name='ratios',
            old_name='company',
            new_name='ticker',
        ),
    ]
