# Generated by Django 2.2.3 on 2019-08-06 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190806_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='cashtable',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='dividends',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='equity',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='incomestatement',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='price',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
        migrations.AlterField(
            model_name='ratios',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
    ]
