# Generated by Django 2.2.4 on 2019-08-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190806_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Date Scraped')),
                ('score', models.FloatField()),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
    ]
