# Generated by Django 2.2.4 on 2019-08-30 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='overviews',
            new_name='overview',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
