# Generated by Django 2.2.4 on 2019-09-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190903_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directors',
            name='director_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='directors',
            name='director_role',
            field=models.CharField(max_length=100),
        ),
    ]
